FROM ghcr.io/pnpm/pnpm:11 AS base

RUN pnpm runtime set node 24 -g

WORKDIR /app

ENV DATABASE_HOST="dummy"
ENV DATABASE_PORT="3306"
ENV DATABASE_USER="dummy"
ENV DATABASE_PASSWORD="dummy"
ENV DATABASE_NAME="dummy"

# --------------------------------------------------
# Dependencies
# --------------------------------------------------

FROM base AS deps

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY apps/bot/package.json ./apps/bot/package.json
COPY apps/web/package.json ./apps/web/package.json
COPY packages/database/package.json ./packages/database/package.json

RUN pnpm install --frozen-lockfile


# --------------------------------------------------
# Builder
# --------------------------------------------------

FROM base AS builder

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/web/node_modules ./apps/web/node_modules
COPY --from=deps /app/packages/database/node_modules ./packages/database/node_modules

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY apps/web ./apps/web
COPY packages/database ./packages/database

COPY prisma.config.ts ./
COPY tsconfig.json ./

RUN pnpm --filter database db:generate

RUN pnpm --filter web build


# --------------------------------------------------
# Runtime
# --------------------------------------------------

FROM base AS runner

WORKDIR /app

COPY certs/ ./certs/

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder /app/apps/web/public ./apps/web/public

EXPOSE 3000

CMD ["node", "apps/web/server.js"]